version: '3'

services:
  cmdb-mongo:
    image: mongo:latest
    container_name: cmdb-mongo
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  cmdb-redis:
    image: redis:latest
    container_name: cmdb-redis
    ports:
      - 6379:6379
    restart: unless-stopped