### 建立团队
POST http://127.0.0.1:8000/api/v1/team
Content-Type: application/json

{
    "team_name": "研发"
}

### 建立用户
POST http://127.0.0.1:8000/api/v1/user
Content-Type: application/json

{
    "user_name": "zhangsan",
    "real_name": "张三",
    "mobile": "138000000001",
    "email": "zhangsan@126.com",
    "password": "123456",
    "team_id": "00000000000000"
}

### 获取单个用户信息
GET http://127.0.0.1:8000/api/v1/user?_id=xxxxxxxx